all:
	g++ -O3 -march=native -std=c++14 error.cpp -o error

run: all
	./error ../testcase/exp_testcase.txt

ml7: all
	./error ../testcase/ml7_testcase.txt

inc: all
	./error ../testcase/inc_testcase.txt

dec: all
	./error ../testcase/dec_testcase.txt

two: all
	./error ../testcase/two_testcase.txt

sum: all
	./error ../testcase/sum_testcase.txt

clean:
	rm error

p1: all
	./error ../hackers-delight/p1.txt

p2: all
	./error ../hackers-delight/p2.txt

p3: all
	./error ../hackers-delight/p3.txt

p4: all
	./error ../hackers-delight/p4.txt

p17: all
	./error ../hackers-delight/p17.txt

